# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: dab-azure-cosmos-db-nosql-quickstart
services:
  api:
    project: ./src/api
    language: python
    host: containerapp
    docker:
      path: Dockerfile
      context: ./
  web:
    project: ./src/web
    language: csharp
    host: containerapp
    docker:
      path: Dockerfile
      context: ./
pipeline:
  provider: github