services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - back-tier
  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
      - AZURE_COSMOS_EMULATOR_ARGS=/alternativenames=cosmos-db
    expose:
      - "8081"
    networks:
      - back-tier
networks:
  back-tier: {}